joelsite/craigs/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    # url(r'^(?P<job_name_id>[0-9]+)$', views.settings, name='settings'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.task_edit, name='task_edit'),
    url(r'^edit_option/$', views.edit_option, name='edit_option'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^new-task$', views.create_task, name='create_task'),
    # url(r'^new-task$', views.create_task, name='create_task'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.task_delete, name='task_delete'),
    url(r'^(?P<pk>[0-9]+)/last-items$', views.last_items, name='last_items'),
]

joelsite/joelsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('craigs.urls', namespace="craigs")),
]

joelsite/craigs/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.utils import timezone


class PersonOptions(models.Model):
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey(User, default=1)
    job_name = models.CharField(max_length=250)
    city = models.CharField(max_length=250, blank=True)
    category = models.CharField(max_length=250, blank=True)
    subcategory = models.CharField(max_length=250, blank=True)
    options = models.CharField(max_length=1000, blank=True)
    keyword = models.CharField(max_length=250, blank=True)
    stop_word = models.CharField(max_length=250, blank=True)
    url = models.CharField(max_length=1000, blank=True, default='')
    time_update = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.job_name


class ScrapedInfo(models.Model):
    user = models.ForeignKey(User, default=1)
    title = models.CharField(max_length=250)
    url = models.CharField(max_length=250)
    job_name = models.ForeignKey(PersonOptions, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class CityOptions(models.Model):
    city = models.CharField(max_length=250)
    state = models.CharField(max_length=250)
    city_for_frontend = models.CharField(max_length=250)

    def __str__(self):
        return self.city_for_frontend


class Options(models.Model):
    category = models.CharField(max_length=250)
    front_category = models.CharField(max_length=250, blank=True)
    subcategory = models.CharField(max_length=250)
    front_subcategory = models.CharField(max_length=250, blank=True)
    option1 = models.CharField(max_length=250, blank=True)
    option2 = models.CharField(max_length=250, blank=True)
    option3 = models.CharField(max_length=250, blank=True)
    option4 = models.CharField(max_length=250, blank=True)
    option5 = models.CharField(max_length=250, blank=True)
    option6 = models.CharField(max_length=250, blank=True)
    option7 = models.CharField(max_length=250, blank=True)
    option8 = models.CharField(max_length=250, blank=True)
    option9 = models.CharField(max_length=250, blank=True)
    option10 = models.CharField(max_length=250, blank=True)
    option11 = models.CharField(max_length=250, blank=True)
    option12 = models.CharField(max_length=250, blank=True)
    option13 = models.CharField(max_length=250, blank=True)
    option14 = models.CharField(max_length=250, blank=True)
    option15 = models.CharField(max_length=250, blank=True)
    front_option1 = models.CharField(max_length=250, blank=True)
    front_option2 = models.CharField(max_length=250, blank=True)
    front_option3 = models.CharField(max_length=250, blank=True)
    front_option4 = models.CharField(max_length=250, blank=True)
    front_option5 = models.CharField(max_length=250, blank=True)
    front_option6 = models.CharField(max_length=250, blank=True)
    front_option7 = models.CharField(max_length=250, blank=True)
    front_option8 = models.CharField(max_length=250, blank=True)
    front_option9 = models.CharField(max_length=250, blank=True)
    front_option10 = models.CharField(max_length=250, blank=True)
    front_option11 = models.CharField(max_length=250, blank=True)
    front_option12 = models.CharField(max_length=250, blank=True)
    front_option13 = models.CharField(max_length=250, blank=True)
    front_option14 = models.CharField(max_length=250, blank=True)
    front_option15 = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.front_subcategory


class CategoryOptions(models.Model):
    category = models.CharField(max_length=250)
    category_for_frontend = models.CharField(max_length=250)

    def __str__(self):
        return self.category_for_frontend


class SubCategoryOptions(models.Model):
    category = models.CharField(default='', max_length=250)  #ForeignKey(CategoryOptions, on_delete=models.CASCADE)
    subcategory = models.CharField(default='', max_length=250)
    subcategory_for_frontend = models.CharField(max_length=250)

    def __str__(self):
        return self.subcategory_for_frontend


class AdditionalOptions(models.Model):
    subcategory = models.CharField(default='', max_length=250)#models.ForeignKey(SubCategoryOptions, on_delete=models.CASCADE)
    option = models.CharField(default='', max_length=250)
    option_for_frontend = models.CharField(default='all', max_length=250)

    def __str__(self):
        return self.option_for_frontend

joelsite/craigs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http.response import HttpResponse
from .models import PersonOptions, CityOptions, SubCategoryOptions, AdditionalOptions, ScrapedInfo
from .forms import OptionsForm, NewTask, UserForm, IsActiveForm, EditOption
from django.utils import timezone
from collections import defaultdict
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail


def last_items(request, pk):
    if not request.user.is_authenticated():
        return render(request, 'craigs/login.html')
    else:
        try:
            scraped_ids = []
            for options in PersonOptions.objects.filter(user=request.user, pk=pk):
                for scraped in options.scrapedinfo_set.all():
                    scraped_ids.append(scraped.pk)
            last_items = ScrapedInfo.objects.filter(pk__in=scraped_ids)
            print(last_items)

        except PersonOptions.DoesNotExist:
            last_items = []
        return render(request, 'craigs/last_items.html', {'last_items': last_items})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                options = PersonOptions.objects.all()
                return render(request, 'craigs/index.html', {'options': options})
            else:
                return render(request, 'craigs/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'craigs/login.html', {'error_message': 'Invalid login'})
    return render(request, 'craigs/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('create_task')

    context = {
        "form": form,
    }
    return render(request, 'craigs/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'craigs/login.html', context)


def home_page(request):
    if not request.user.is_authenticated():
        return render(request, 'craigs/login.html')
    if request.method == "POST":
        form = IsActiveForm(request.POST)

        if form.is_valid():

            get_object_or_404(PersonOptions, pk=pk)

            task = form.save(commit=False)
            task.is_active = request.is_active
            task.time_update = timezone.now()
            task.save()
            return redirect('/')
    else:
        form = IsActiveForm()

    options = PersonOptions.objects.filter(user=request.user)
    return render(request, 'craigs/index.html', {'options': options, 'form': form})


def edit_option(request):
    if not request.user.is_authenticated():
        return render(request, 'craigs/login.html')
    if request.method == "POST":
        form = EditOption(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            p = PersonOptions.objects.get(pk=data['pk'])
            p.is_active = data['is_active']
            p.save()
            # for (question, answer) in form.extra_answers():
            #     print(question, answer)
            print('================')
            print(form.cleaned_data)
            return redirect('/')


def task_edit(request, pk):
    if not request.user.is_authenticated():
        return render(request, 'craigs/login.html')
    task = get_object_or_404(PersonOptions, pk=pk)

    if request.method == "POST":
        form = OptionsForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.time_update = timezone.now()
            task.save()
            return redirect('/')

    else:
        form = OptionsForm(instance=task)
    return render(request, 'craigs/task_edit.html', {'form': form})


def task_delete(request, pk):
    print(pk)
    option = PersonOptions.objects.get(pk=pk)
    option.delete()
    return redirect('/')


def create_task(request):
    if not request.user.is_authenticated():
        return render(request, 'craigs/login.html')
    cities = CityOptions.objects.values()
    subcategories = SubCategoryOptions.objects.values()
    options = AdditionalOptions.objects.values()
    o = defaultdict(list)
    for option in options:
        for k, v in option.items():
            if {option['option_for_frontend']: option['option']} not in o[option['subcategory']]:
                o[option['subcategory']].append({option['option_for_frontend']: option['option']})
    additional_options = dict(o)
    d = defaultdict(list)
    for s in subcategories:
        for k, v in s.items():
            if {s['subcategory_for_frontend']: s['subcategory']} not in d[s['category']]:
                d[s['category']].append({s['subcategory_for_frontend']: s['subcategory']})
    categories = dict(d)
    cc = defaultdict(list)
    for c in cities:
        for k, v in c.items():
            if {c['city_for_frontend']: c['city']} not in cc[c['state']]:
                cc[c['state']].append({c['city_for_frontend']: c['city']})
    cities = dict(cc)
    # print('================')
    # print(cities)
    # print('================')
    if request.method == "POST":
        form = NewTask(request.POST)
        if form.is_valid():
            print('================')
            print(form)
            print(form.cleaned_data)
            data = form.cleaned_data
            options = ''
            for k, v in data.items():
                if k[:3] == 'opt' and v != '':
                    options += options + '&' + v
            print (options)
            if data.get('job_name', '') == '':
                form = OptionsForm()
                error_massege = 'Name of task is empty'
                print('================')
                return render(request, 'craigs/task_edit.html', {
                    'form': form,
                    'error_massege': error_massege,
                    'cities': cities,
                    'categories': categories,
                    'additional_options': additional_options
                })
            if data.get('category', '') != '' and data.get('subcategory', '') == '':
                form = OptionsForm()
                error_massege = 'Please, choose an subcategory'
                print('================')
                return render(request, 'craigs/task_edit.html', {
                    'form': form,
                    'error_massege': error_massege,
                    'cities': cities,
                    'categories': categories,
                    'additional_options': additional_options
                })
            p = PersonOptions(
                user=request.user,
                options=options,
                is_active=True,#data['is_active'],
                city=data.get('village', ''),
                job_name=data.get('job_name', ''),
                category=data.get('category', ''),
                subcategory=data.get('subcategory', ''),
                keyword=data.get('keyword', ''),
                stop_word=data.get('stop_word', ''),
                url=data.get('url1', ''),
            )
            p.save()
            send_mail(
                'Created new task: {}'.format(data.get('job_name', '')),
                'Task "{}" is active'.format(data.get('job_name', '')),
                'mykhailo.kuznietsov@gmail.com',
                [p.user.email],
                fail_silently=False,
                # html_message=message
            )
            print("--------")
        else:
            form = OptionsForm()
            error_massege = 'Name of task is empty'
            print('================')
            return render(request, 'craigs/task_edit.html', {
                'form': form,
                'error_massege': error_massege,
                'cities': cities,
                'categories': categories,
                'additional_options': additional_options
            })

        # task = form.save(commit=False)
        # task.user = request.user
        # task.time_update = timezone.now()
        # task.save()
        return redirect('/')

    else:
        form = OptionsForm()
    print('================')
    return render(request, 'craigs/task_edit.html', {
        'form': form,
        'cities': cities,
        'categories': categories,
        'additional_options': additional_options
    })

joelsite/craigs/templates/craigs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="initial-scale=1, width=device-width" name="viewport">
    <title>{% block title %}List of tasks{% endblock %}</title>
    {% load staticfiles %}

    <!--<link rel="stylesheet" type="text/css" href="{% static 'craigs/bootstrap.min.css' %}">-->

    <!--<script src="{% static 'craigs/js/bootstrap.min.js' %}"></script>-->
    <!--<script src="{% static 'craigs/js/scripts.js' %}"></script>-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<!--<script src="{% static 'craigs/styles.css' %}"></script>-->
    <link rel="stylesheet" type="text/css" href="{% static 'craigs/styles.css' %}">

</head>
<body>

<div class="container">
 <ul class="nav justify-content-center">
                    <li class="nav-item"><a class="nav-link" href="{% url 'craigs:home' %}">List of tasks</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'craigs:create_task' %}">Create new task</a></li>

                    <li class="nav-item"><a  class="nav-link" href="{% url 'craigs:logout_user' %}"><strong>Log Out</strong></a></li>
                </ul>
            <div id="top">

                <!--<div>-->
                    <!--<a href="{% url 'craigs:home' %}"><img alt="Image" src="https://finance.cs50.net/img/logo.png"></a>-->
                <!--</div>-->



            </div>
</div>
{% block body %}
{% endblock %}


</body>
</html>

joelsite/craigs/templates/craigs/index.html
{% extends 'craigs/base.html' %}
{% block title %}List of Tasks{% endblock %}
{% block body %}

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}
{% if options %}
<h2 class="middle">
    List of tasks:
</h2>
<br>
<div class="card-columns">
{% for option in options %}
<div class="card ">
  <div class="card-header">
      <a href="{% url 'craigs:last_items' option.id %}" >{{option.job_name}}</a>
  </div>
  <div class="card-block">
    <h4 class="card-title">{{option.category}}</h4>
      {% if not option.keyword %}
      <br>
      {% endif %}
      {% if not option.category %}
      <br>
      {% endif %}
      <h6 class="card-subtitle mb-2 text-muted">{{option.keyword}}</h6>
      <small class="text-muted"><a href="{% url 'craigs:task_delete' option.id %}" class="card-link">Delete</a> </small>
      <form method="post" action="{%url 'craigs:edit_option' %}" >
          {% csrf_token %}
          <input name="is_active" {% if option.is_active %}checked=""{% endif %} type="checkbox">Active job
          <input name="pk" hidden="" type="text" value="{{option.pk}}">

    <input class="btn btn-primary" type="submit" value="Save">
    </form>
  </div>
</div>
 {% endfor %}
{% endif %}



{% endblock %}

joelsite/craigs/templates/craigs/last_items.html
{% extends 'craigs/base.html' %}
{% block title %}Last items{% endblock %}
{% block body %}

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}
<div class="middle">

<br>

<table class = "table table-striped">
   <caption>Last items</caption>

   <thead>
      <tr>
         <th>Items</th>
      </tr>
   </thead>

   <tbody>
   {% for last_item in last_items %}
      <tr>

         <td><a href="{{last_item.url}}">{{last_item.title}}</a></td>

      </tr>
{% endfor %}

   </tbody>

</table>
    </div>

{% endblock %}

joelsite/craigs/templates/craigs/login.html
{% extends 'craigs/base.html' %}
{% block title %}Log in{% endblock %}
{% block body %}

<div id="middle">
    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
<form action="{% url 'craigs:login_user'%}"  method="post" enctype="multipart/form-data">
    <fieldset>
        {% csrf_token %}
        <div class="form-group">
            <input autocomplete="off" autofocus="" class="form-control" name="username" placeholder="Username" type="text">
        </div>
        <div class="form-group">
            <input class="form-control" name="password" placeholder="Password" type="password">
        </div>
        <div class="form-group">
            <button class="btn btn-default" type="submit">
                <span aria-hidden="true" class="glyphicon glyphicon-log-in"></span>
                Log In
            </button>
        </div>
    </fieldset>
</form>
<div>
    or <a href="{% url 'craigs:register' %}">register</a> for an account
</div>
</div>

{% endblock %}

joelsite/craigs/templates/craigs/register.html
{% extends 'craigs/base.html' %}
{% block title %}Register{% endblock %}
{% block body %}

<div id="middle">
<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <div class="form-group">
            <div>
                <div class="form-group">
                    <input autocomplete="off" autofocus="" class="form-control" name="username" placeholder="Username" type="text">
                </div>
                <div class="form-group">
                    <input class="form-control" name="password" placeholder="Password" type="password">
                </div>
                <div class="form-group">
                    <input class="form-control" name="email" placeholder="Email" type="email">
                </div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-default" type="submit">Register</button>
        </div>
    </fieldset>
</form>
<div>
    or <a href="{% url 'craigs:login_user' %}">log in</a>
</div>
            </div>

{% endblock %}

joelsite/craigs/templates/craigs/task_edit.html
{% extends 'craigs/base.html' %}
{% load my_text %}
{% block title %}List of Tasks{% endblock %}
{% block body %}



<div id="middle">
    <Select id="mainselector" style="width: 170px">
        <option disabled="" selected="" value="">options</option>
       <option value="without_url">without_url</option>
       <option value="with_url">with_url</option>

    </Select>

<form  method="post" action="{%url 'craigs:create_task' %}" enctype="multipart/form-data">
        {% csrf_token %}
    {% if error_massege %}
    <p class="alert alert-warning"><strong>{{error_massege}}</strong></p>
    {% endif %}
    <input style="width: 170px" name="job_name" type="text" placeholder="name of task">
    <br>
    <input style="width: 170px" name="stop_word" type="text" placeholder="negative keywords">

<div id="with_url" class="variants" style="display:none">
    <br>

    <input style="width: 170px" name="url1" type="text" placeholder="link">
    <!--<br>-->
    <!--<input style="width: 170px" name="stop_word" type="text" placeholder="negative keywords">-->
    <br>
    <br>
    <input class="btn btn-primary" type="submit" value="Create Task">

</div>
<div id="without_url" class="variants" style="display:none">
    <br>
    <select style="width: 170px" id="state" name="state">
       <option disabled="" selected="" value="">state</option>
                    </select>
                    <br/>
    <select style="width: 170px" id="cities" name="village">
        <!--<option disabled="" selected="" value="">subcategory</option>-->
    </select>
<br>
    <br/>
   <select style="width: 170px" id="firstmenu" name="category">
       <option disabled="" selected="" value="">category</option>
                    </select>
                    <br/>
    <select style="width: 170px" id="secondmenu" name="subcategory">
        <!--<option disabled="" selected="" value="">subcategory</option>-->
    </select>
<br>

    <!--<input name="keyword" type="text" placeholder="search keyword"/>-->
   <input style="width: 170px" name="keyword" maxlength="250" id="id_keyword" type="text" placeholder="search keyword">
    <br>
{% for key, value in additional_options.items %}
<label class="{{key|replace_plus}}">
{% for q in value %}
    {% with forloop.counter as n %}
    {{forloop.counter}}
    {% for k,v in q.items %}

                        <input name="option{{n}}"  value="{{v}}" type="checkbox">
                        {{k}}
    <br>
    {% endfor %}
    {% endwith %}
    {% endfor %}
                        </label>

{% endfor %}
    <br>

    <input class="btn btn-primary" type="submit" value="Create Task">
    </div>
</form>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
------------------------------------------------------


<script type="text/javascript">
var items = [
    {% for key, value in categories.items %}
    {
        name:'{{key}}',
        value: '{{key}}',
        subitems: [
        {name: '---', value: '', disabled: '', selected: ''},
        {% for val in value %}
        {% for a,b in val.items %}
            {name: '{{a}}', value: '{{b}}'},
        {% endfor %}
        {% endfor %}
        ]
    },
    {% endfor %}

];
var items2 = [
    {% for key, value in cities.items %}
    {
        name:'{{key}}',
        value: '{{key}}',
        subitems: [
        {name: '---', value: '', disabled: '', selected: ''},

            {% for val in value %}
        {% for a,b in val.items %}
            {name: '{{b}}', value: '{{a}}'},
        {% endfor %}
        {% endfor %}

        ]
    },
    {% endfor %}

];
$(function(){
    var temp = {};

    $.each(items2, function(){
        $("<option />")
        .attr("value", this.value)
        .attr('style', 'width: 170px')
        .html(this.name)
        .appendTo("#state");
        temp[this.value] = this.subitems;
    });

    $("#state").change(function(){
        var value = $(this).val();
        var menu = $("#cities");

        menu.empty();
        $.each(temp[value], function(){
            $("<option />")
            .attr("value", this.value)
            .attr('style', 'width: 170px')
            .html(this.name)
            .appendTo(menu);
        });
    }).change();

});
$(function(){
    var temp = {};

    $.each(items, function(){
        $("<option />")
        .attr("value", this.value)
        .attr('style', 'width: 170px')
        .html(this.name)
        .appendTo("#firstmenu");
        temp[this.value] = this.subitems;
    });

    $("#firstmenu").change(function(){
        var value = $(this).val();
        var menu = $("#secondmenu");

        menu.empty();
        $.each(temp[value], function(){
            $("<option />")
            .attr("value", this.value)
            .attr('style', 'width: 170px')
            .html(this.name)
            .appendTo(menu);
        });
    }).change();


});
{% for key, value in additional_options.items %}
$(".{{key|replace_space}}").hide();
console.log("{{key|replace_space}}");
{% endfor %}
<!--$(".hasPic").hide();-->

$("#secondmenu").change(function() {
    if($(this).find('option:selected').text() == "ofc") {

        $(".hasPic").show();
    }
    {% for key, value in additional_options.items %}
    else if ($(this).find('option:selected').text() == "{{key}}"){
    $(".{{key|replace_space}}").show().siblings("label").hide();
    }
    {% endfor %}
    else {
        {% for key, value in additional_options.items %}
    $(".{{key}}").hide();
    {% endfor %}
    }
});

$(function() {
        $('#mainselector').change(function(){
            $('.variants').hide();
            $('#' + $(this).val()).show();
        });
    });
<!--$(".answer").hide();-->
<!--$(".coupon_question").click(function() {-->
    <!--if($(this).is(":checked")) {-->
        <!--$(".answer").show();-->
    <!--} else {-->
        <!--$(".answer").hide();-->
    <!--}-->
<!--});-->
</script>
</div>
{% endblock %}